# Generated by Django 5.1.6 on 2025-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_language',
            field=models.CharField(choices=[('as', 'Assamese'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('or', 'Odia'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh-cn', 'Chinese (Simplified)'), ('zh-tw', 'Chinese (Traditional)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ru', 'Russian'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ar', 'Arabic')], default='en', max_length=10),
        ),
    ]
