# Generated by Django 5.1.6 on 2025-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_message_content_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('ta', 'Tamil'), ('te', 'Telugu'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
