# Generated by Django 5.1.6 on 2025-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_alter_message_content_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_time']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='message_file',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content_language',
            new_name='receiver_language',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='receiver_msg',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='sent_time',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('ta', 'Tamil'), ('te', 'Telugu'), ('en', 'English')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('voice', 'Voice')], default='text', max_length=10),
        ),
    ]
